
# Use a base image with the desired Neo4j version
FROM neo4j:4.3.3

# Expose the necessary ports
EXPOSE 7474 7473 7687

# Set environment variables for Neo4j credentials
ENV NEO4J_AUTH=neo4j/password

# Start Neo4j
CMD ["neo4j"]
